blueprint:
  name: Motion Light With Dimming
  description: Turn a light on based on detected motion, dim lights before turning off
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: This sensor will be synchronized with the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
  
trigger:
  - platform: state
    entity_id:
    - !input motion_sensor
    to: "on"
    from: "off"
    id: "on"
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.eteinen_ajastin_dim
    id: dim
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.eteinen_ajastin_off
    id: "off"

