blueprint:
  name: Motion Light With Dimming (Advanced)
  description: Turn a light on based on detected motion, dim lights before turning off. Optional door sensor support to control motion sensor based on door state, and optional conditional brightness.
  domain: automation
  source_url: https://github.com/mrauhala/homeassistant/blob/main/blueprints/motion-lights-advanced.yaml
  author: Mikko Rauhala
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor that will be synchronized with the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    motion_switch:
      name: Motion Sensor Switch (Optional)
      description: Switch to control the motion sensor on/off. Only used if door sensor is also configured.
      default: {}
      selector:
        entity:
          domain: switch
    door_sensor:
      name: Door Sensor (Optional)
      description: Door sensor that controls motion sensor behavior. When door closes with motion detected, motion sensor is disabled. When door opens, motion sensor is re-enabled.
      default: {}
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    target_light:
      name: Lights
      description: The lights to keep in sync.
      selector:
        target:
          entity:
            domain: light
    off_timer:
      name: Off Timer
      description: Time to keep the lights dimmed before turning off.
      selector:
        entity:
          domain: timer
    on_timer:
      name: On Timer
      description: Time to keep the lights on after last motion has cleared.
      selector:
        entity:
          domain: timer
    on_level:
      name: On Level
      description: Use this brightness when lights are on.
      default: 100
      selector:
        number:
          max: 100
          min: 1
          unit_of_measurement: "%"
          mode: slider
    conditional_entity:
      name: Conditional Entity (Optional)
      description: Entity to check for conditional brightness. When this entity is 'on', the alternative brightness will be used instead of the normal on level.
      default: {}
      selector:
        entity:
    conditional_on_level:
      name: Conditional On Level (Optional)
      description: Use this brightness when lights are on and the conditional entity is 'on'. Only applies if Conditional Entity is set.
      default: 50
      selector:
        number:
          max: 100
          min: 1
          unit_of_measurement: "%"
          mode: slider
    dim_level:
      name: Dim Level
      description: Lights dim to this level to indicate soon before turning off lights.
      default: 50
      selector:
        number:
          max: 100
          min: 1
          unit_of_measurement: "%"
          mode: slider
  
trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: "on"
  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    from: "on"
    id: clear
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input on_timer
    id: dim
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input off_timer
    id: "off"
  - platform: state
    entity_id: !input door_sensor
    from: "off"
    to: "on"
    id: dooropen

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ conditional_entity != none and conditional_entity != '' }}"
                  - condition: state
                    entity_id: !input conditional_entity
                    state: "on"
                sequence:
                  - service: light.turn_on
                    data:
                      brightness_pct: !input conditional_on_level
                    target: !input target_light
            default:
              - service: light.turn_on
                data:
                  brightness_pct: !input on_level
                target: !input target_light
          - service: timer.cancel
            data: {}
            target:
              entity_id: 
                - !input on_timer
          - service: timer.cancel
            data: {}
            target:
              entity_id:
                - !input off_timer
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ door_sensor != none and door_sensor != '' and motion_switch != none and motion_switch != '' }}"
                  - condition: state
                    entity_id: !input door_sensor
                    state: "off"
                sequence:
                  - service: switch.turn_off
                    data: {}
                    target: 
                      entity_id: !input motion_switch
              - conditions:
                  - condition: template
                    value_template: "{{ door_sensor != none and door_sensor != '' and motion_switch != none and motion_switch != '' }}"
                  - condition: state
                    entity_id: !input door_sensor
                    state: "on"
                sequence:
                  - service: switch.turn_on
                    data: {}
                    target: 
                      entity_id: !input motion_switch
      - conditions:
          - condition: trigger
            id: dim
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: !input dim_level
            target: !input target_light
          - service: timer.start
            data: {}
            target:
              entity_id: 
                - !input off_timer
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: light.turn_off
            data:
              transition: 10
            target: !input target_light
      - conditions:
          - condition: trigger
            id: clear
        sequence:
          - service: timer.start
            data: {}
            target:
              entity_id:
                - !input on_timer
          - service: timer.cancel
            data: {}
            target:
              entity_id:
                - !input off_timer
      - conditions:
          - condition: trigger
            id: dooropen
          - condition: template
            value_template: "{{ door_sensor != none and door_sensor != '' and motion_switch != none and motion_switch != '' }}"
        sequence:
          - service: switch.turn_on
            data: {}
            target: 
              entity_id: !input motion_switch
mode: single
